// Register PWA service worker (generated by vite-plugin-pwa)
import { registerSW } from "virtual:pwa-register";

registerSW({ immediate: true });

import { Capacitor } from "@capacitor/core";
import { UNAUTHED_ERR_MSG } from "@shared/const";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { httpBatchLink, TRPCClientError } from "@trpc/client";
import { createRoot } from "react-dom/client";
import superjson from "superjson";
import { trpc } from "@/lib/trpc";
import App from "./App";
import { getLoginUrl } from "./const";
import "./index.css";
import { supabase } from "@/contexts/AuthContext";

const analyticsEndpoint = import.meta.env.VITE_ANALYTICS_ENDPOINT;
const analyticsWebsiteId = import.meta.env.VITE_ANALYTICS_WEBSITE_ID;

if (analyticsEndpoint && analyticsWebsiteId) {
  const script = document.createElement("script");
  script.defer = true;
  script.src = `${analyticsEndpoint.replace(/\/$/, "")}/umami`;
  script.dataset.websiteId = analyticsWebsiteId;
  document.body.appendChild(script);
}

// ─── React Query Caching Strategy ────────────────────────────────────────────
// • staleTime: how long data is considered fresh (no re-fetch on mount/focus)
// • gcTime:    how long unused cache entries are kept in memory
//
// Defaults are conservative (5 min stale / 10 min gc).
// Per-query overrides are done via query-key conventions in individual
// trpc.*.useQuery() calls (see ProfilePage, HistoryPage, DashboardPage).
// ─────────────────────────────────────────────────────────────────────────────
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Data is fresh for 5 minutes — no re-fetch when switching pages
      staleTime: 5 * 60 * 1000,
      // Keep unused cache entries for 10 minutes before GC
      gcTime: 10 * 60 * 1000,
      // Don't refetch on window focus (mobile PWA behaviour)
      refetchOnWindowFocus: false,
      // Retry failed queries up to 3 times with exponential backoff (Circuit Breaker approach)
      retry: 3,
      retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    },
    mutations: {
      // Mutations don't retry by default to avoid double-submits
      retry: false,
    },
  },
});
const trpcUrl =
  import.meta.env.VITE_TRPC_URL ??
  (Capacitor.isNativePlatform()
    ? "https://pawra.vercel.app/api/trpc"
    : "/api/trpc");

const redirectToLoginIfUnauthorized = (error: unknown) => {
  if (!(error instanceof TRPCClientError)) return;
  if (typeof window === "undefined") return;

  const isUnauthorized = error.message === UNAUTHED_ERR_MSG;

  if (!isUnauthorized) return;

  window.location.href = getLoginUrl();
};

queryClient.getQueryCache().subscribe((event) => {
  if (event.type === "updated" && event.action.type === "error") {
    const error = event.query.state.error;
    redirectToLoginIfUnauthorized(error);
    console.error("[API Query Error]", error);
  }
});

queryClient.getMutationCache().subscribe((event) => {
  if (event.type === "updated" && event.action.type === "error") {
    const error = event.mutation.state.error;
    redirectToLoginIfUnauthorized(error);
    console.error("[API Mutation Error]", error);
  }
});

const trpcClient = trpc.createClient({
  links: [
    httpBatchLink({
      url: trpcUrl,
      transformer: superjson,
      async headers() {
        if (supabase) {
          const { data } = await supabase.auth.getSession();
          if (data.session?.access_token) {
            return {
              Authorization: `Bearer ${data.session.access_token}`,
            };
          }
        }
        return {};
      },
      fetch(input, init) {
        return globalThis.fetch(input, {
          ...(init ?? {}),
          credentials: "include",
        });
      },
    }),
  ],
});

import { NuqsAdapter } from "nuqs/adapters/react";

createRoot(document.getElementById("root")!).render(
  <trpc.Provider client={trpcClient} queryClient={queryClient}>
    <QueryClientProvider client={queryClient}>
      <NuqsAdapter>
        <App />
      </NuqsAdapter>
    </QueryClientProvider>
  </trpc.Provider>,
);

// ─── Core Web Vitals Reporting ───────────────────────────────────────────────
// Measures LCP, FCP, CLS, TTFB, and INP. Logs to console in dev mode.
// Extend `reportVital` to send metrics to your analytics endpoint in prod.
// ─────────────────────────────────────────────────────────────────────────────
import { type Metric, onCLS, onFCP, onINP, onLCP, onTTFB } from "web-vitals";

function reportVital(metric: Metric) {
  if (import.meta.env.DEV) {
    const emoji =
      metric.rating === "good" ? "✅" : metric.rating === "poor" ? "❌" : "⚠️";
    console.log(
      `%c[WebVital] ${emoji} ${metric.name}: ${Math.round(metric.value)} (${metric.rating ?? "–"})`,
      "color: #6ee7b7; font-weight: bold;",
    );
  }
  // Production hook — uncomment to send to your analytics:
  // fetch('/api/vitals', { method: 'POST', body: JSON.stringify(metric) });
}

onCLS(reportVital);
onFCP(reportVital);
onINP(reportVital);
onLCP(reportVital);
onTTFB(reportVital);
