import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { Button } from "@/components/ui/button";
import { FileText } from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";
import { STATE_EMOJIS } from "../../../shared/types";

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'Helvetica', fontSize: 12 },
  header: { fontSize: 18, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  section: { margin: 10, padding: 10 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 8 },
  date: { width: '25%' },
  state: { width: '45%' },
  confidence: { width: '30%' },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 10, color: 'grey' }
});

const VetReportDocument = ({ stats, animalName, t, isPt }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>{isPt ? "Relatório Veterinário" : "Vet Report"} - {animalName}</Text>
      
      <View style={styles.section}>
        <View style={[styles.row, { fontWeight: 'bold', backgroundColor: '#f9fafb' }]}>
          <Text style={styles.date}>{isPt ? "Data" : "Date"}</Text>
          <Text style={styles.state}>{isPt ? "Estado Predominante" : "Dominant State"}</Text>
          <Text style={styles.confidence}>{isPt ? "Confiança" : "Confidence"}</Text>
        </View>
        
        {stats?.dailyActivity?.map((day: any, i: number) => {
          const states = day.stateBreakdown;
          let dominantState = "relaxed";
          let maxCount = -1;
          for (const s in states) {
            if (states[s] > maxCount) {
              maxCount = states[s];
              dominantState = s;
            }
          }
          const confidenceLabel = day.avgConfidence >= 0.75 ? (isPt ? "Alta" : "High") : day.avgConfidence >= 0.5 ? (isPt ? "Média" : "Medium") : (isPt ? "Baixa" : "Low");
          
          return (
            <View key={i} style={styles.row}>
              <Text style={styles.date}>{new Date(day.date).toLocaleDateString()}</Text>
              <Text style={styles.state}>{STATE_EMOJIS[dominantState as keyof typeof STATE_EMOJIS]} {t(`states.${dominantState}` as any)}</Text>
              <Text style={styles.confidence}>{confidenceLabel}</Text>
            </View>
          );
        })}
      </View>
      
      <Text style={styles.footer}>
        {isPt ? "Gerado pelo PeloNaRoupa — segunda opinião, não substitui diagnóstico veterinário." : "Generated by PeloNaRoupa — second opinion, does not replace a veterinary diagnosis."}
      </Text>
    </Page>
  </Document>
);

export function VetReportButton({ stats, animalName }: { stats: any, animalName: string }) {
  const { t, language } = useLanguage();
  const isPt = language === "pt";

  if (!stats?.dailyActivity || stats.dailyActivity.length === 0) {
    return null;
  }

  return (
    <PDFDownloadLink 
      document={<VetReportDocument stats={stats} animalName={animalName} t={t} isPt={isPt} />} 
      fileName={`pawra_report_${animalName.toLowerCase()}.pdf`}
    >
      {({ loading }) => (
        <Button size="sm" variant="outline" className="gap-2 text-xs rounded-xl border-primary/20 text-primary hover:bg-primary/5 shadow-sm" disabled={loading}>
          <FileText size={14} />
          {loading ? (isPt ? "A gerar..." : "Generating...") : (isPt ? "Relatório Veterinário" : "Vet Report")}
        </Button>
      )}
    </PDFDownloadLink>
  );
}
